INSERT INTO `antibiotics` (`id`, `name`) VALUES
(1, 'Amikacin'),
(2, 'Ampicillin'),
(3, 'Augmentin'),
(4, 'Cefotaxime'),
(5, 'Ceftazidime'),
(6, 'Ceftriaxone'),
(7, 'Ceftizoxime'),
(8, 'Cefuroxime'),
(9, 'Cefuroxime oral'),
(10, 'Chloramphenicol'),
(11, 'Ciprofloxacin'),
(12, 'Co-trimoxazole'),
(13, 'Gentamicin'),
(14, 'Imipenem'),
(15, 'Meropenem'),
(16, 'Nalidixic acid'),
(17, 'Peperacillintazobactam'),
(18, 'Piperacillin'),
(19, 'Nitrofurantoin'),
(20, 'Trimethoprim'),
(21, 'Amoxycillin'),
(22, 'Cefepime'),
(23, 'Colistin'),
(24, 'Tetracycline'),
(25, 'Erythromycin'),
(26, 'Clindamycin'),
(27, 'Vancomycin'),
(28, 'Linezolid'),
(29, 'Penicillin G'),
(30, 'Cefoxitin'),
(31, 'Rifampicin'),
(32, 'Streptomycin'),
(33, 'Minocycline'),
(34, 'Cefexime'),
(35, 'spectinomycin'),
(36, 'Oxacillin'),
(37, 'Levofloxacin'),
(38, 'Cefuroxime Parentral'),
(39, 'High level Gentamicin');
